### PR TITLE
Add version-info cli option

### PR DESCRIPTION
**Pull request by nickjmiller**
My website is set up so that my PWA will pull updates if the version has been incremented. This means that my workflow usually involves incrementing the version before a big change and it'd be nice to keep track of which version is live. An option on the CLI to include this in the commit message would be nice to have.

I am not entirely sure how to test this myself, the logic seems pretty simple but I'm happy to test this with some guidance.

### CODE REVIEW

**Comment by kevmoo** [comment]
Hey @nickjmiller – start by looking at the CI failures

**Comment by nickjmiller** [comment]
I updated the failing test and ran this from my flutter project directory:

`dart run ..\peanut.dart\bin\peanut.dart --version-info`, output was:

```
  Built web

  Version: 0.0.24+1


  Branch: main
  Commit: {}

  package:peanut 5.1.0
```

**Comment by nickjmiller** [comment]
Did not realize that file was generated, sorry new to dart.

**Comment by kevmoo** [comment]
@nickjmiller – you're doing great!

**Comment by nickjmiller** [comment]
Alright I think I figured out the workflow now. Ran `dart test` and `dart run ${peanutDir}/bin/peanut.dart --version-info` from a dart workspace and saw the expected output.

**Pull request merged**
